import * as React from "react";
import { createPortal } from "react-dom";
import { Bitter } from "next/font/google";
import { AnimatePresence, motion } from "framer-motion";
import Stack from "@mui/material/Stack";
import Divider from "@mui/material/Divider";
import { Button, Chip, Stack as MuiStack, IconButton } from "@mui/material";
import GitHubIcon from "@mui/icons-material/GitHub";
import SmartphoneIcon from "@mui/icons-material/Smartphone";
import CloseIcon from "@mui/icons-material/Close";
import Typography from "@mui/material/Typography";
// modal uses CSS module styles; text colors follow MUI theme
import styles from "@/styles/Home.module.css";
import { useTheme, alpha } from "@mui/material/styles";
import Grid from "@mui/material/Grid";

const bitter = Bitter({ subsets: ["latin"], display: "swap" });

const projects = [
  {
    title: "Fetch Robot (2024)", 
    content:
      "Loaded the Fetch robot in simulation utilizing ROS Bridge and interactive hierarchy traversal to render custom\
      URDF files. Implemented forward kinematics with LU decomposition routines to enable robot trajectory execution.\
      Enabled posing robot end-effectors using inverse kinematics via gradient descent with Jacobian transpose.\
      Integrated resolved-rate inverse kinematics with null space constraints to respective joint limits and Cyclic\
      Coordinate Descent (CCD) inverse kinematics algorithm. Developed collision detection algorithm and both RRT-\
      Connect and RRT-Star motion planner for robot navigation.",
    url: "disabled",
    tags: ["Robotics", "ROS", "Kinematics"],
  },
  {
    title: "Minap (2023)",
    content:
      "Code and documentation for Mi Nap sleep diary smartwatch app and related infrastructure, \
    developed by the 2023 ITS intern cohort at the University of Michigan. This Fitbit / Apple Watch / Garmin \
    smartwatch app allows clinical research participants to keep a sleep diary on their watch, with the data \
    being securely transferred to a staging cloud storage service, and then to an Oracle PL/SQL database that \
    sits behind a firewall.",
    url: "https://github.com/DepressionCenter/MiNap",
    tags: ["Mobile", "Health", "Full Stack"],
  },
  {
    title: "Insta Clone (2023)",
    content:
      "Program an dockerized instagram clone that uses AWS RDS PostgreSQL database, AWS S3, and AWS \
    CloudFront CDN for serving resources and handling uploads. Provision cloud infrastructure leveraging AWS \
    CloudFormation. Configure load balancer and security groups on AWS EC2. Set up a Github actions CI/CD pipeline \
    to update images on AWS ECR, register task definition and deploy application service on AWS ECS with AWS Fargate. ",
    url: "disabled",
    tags: ["Cloud", "AWS", "DevOps"],
  },
  {
    title: "pSSID (2023)",
    content:
      "pSSID is the engine that runs UMich ITS's newest project of implementing a full-stack web application\
    on perfSONAR, an open source network analytics tool. UMich is actively contributing to the project to make it \
    possible to run on enterprise networks across research and higher education insitutions. I'm in charge of provisioning \
    this engine on hardware Raspberry 4 probes. My script creates a daemonized process of continuously processing json config \
    files generated by the application and passes the test information to perfSONAR.",
    url: "https://github.com/UMNET-perfSONAR/pSSID2",
    tags: ["Networking", "Open Source", "Systems"],
  },
  {
    title: "ROS SAM Client (2023)",
    content:
      "Devise an image segmentation ROS service for real-time segmentation mask generation with using OpenCV,\
    PyTorch and NumPy. Design a GUI that allows customizable segmentation and manage multi-processes between GUI and ROS service.\
    Separate local ROS service from the server hosting the segmentation model and provisioned server setup with Terraform.",
    url: "https://github.com/maxliu2001/SAM-ROS-Client-Server",
    tags: ["Computer Vision", "ROS", "ML"],
  },
  {
    title: "ZotMeal (2021)",
    content:
      "ZotMeal obtains a daily menu from the web and then displays it in a friendly user-interface.\
    Both Brandywine and Anteatery’s menu is included with the most up-to-date information! Dining hall \
    service hours can also be found in the app. Moreover, users are able to do a quick Google search on \
    the food simply by clicking the menu. I'm in charge of writing the web scraper of the app's backend. \
    The app is published and currently has 5000+ users.",
    url: "https://github.com/maxliu2001/ZotMeal/tree/master",
    tags: ["Mobile", "Scraping"],
  },
  {
    title: "SnapShare (2021)",
    content:
      "SnapShare uses machine learning to make donating your surplus food super easy. There are only \
    2 steps: Snap and Share. Snap a pic of your surplus food, and the machine learning model will automatically \
    classify it and match a local food bank that needs it. This is the UVA Hackathon Social Empowerment Track Winner.",
    url: "https://github.com/maxliu2001/SnapShare",
    tags: ["ML", "Hackathon", "Social Good"],
  },
  {
    title: "Pomodoro Cat (2021)",
    content:
      "Working remotely can be challenging, especially amidst a worldwide pandemic. After analyzing the \
    current applications that target productivity, we decide to integrate a fun game that allows users to keep \
    their own cats while keeping track of their time using Pomodoro technique. This won the VTech Hackathon 2nd best \
    overall. ",
    url: "https://github.com/stanford-rejects/PomodoroCat",
    tags: ["Productivity", "Game", "Hackathon"],
  },
  {
    title: "CodeAI (2021-2022)",
    content:
      "This project integrates a natural language processor into a website using React.js, next.js and \
    Firebase in order to build a learning platform for lower income elementary school students in Santa Ana, CA \
    to learn AI literacy and possibly embark academic persuit in computer science. I worked on this project while \
    serving as a research assistant at UCI Digital Learning Lab",
    url: "https://github.com/codeAI-Project/codeAI-Lab",
    tags: ["Education", "Web", "NLP"],
  },
];

const enterAnimation = {
  hidden: { opacity: 0, y: 200 },
  visible: {
    y: 20,
    opacity: 1,
    transition: { type: "spring", duration: 1.5 },
  },
};

export default function ProjectsPage() {
  const [active, setActive] = React.useState(null);
  const theme = useTheme();

  const extractYear = (title) => {
    const m = title.match(/\((\d{4}(?:-\d{4})?)\)/);
    return m ? m[1] : null;
  };

  return (
      <Stack direction="column" spacing={5} padding={5}>
        <motion.div
          className="div-container"
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false, amount: 0.8 }}
        >
          <motion.section variants={enterAnimation}>
            <Grid
              container
              spacing={{ xs: 2, md: 2 }}
              className={styles.projectheader}
              padding={1}
              >
                <Grid xs={12}>
                  <Typography
                      component="h1"
                      sx={{ textAlign: "center", mb: { xs: 1, md: 1 } }}
                  >
                      Projects
                  </Typography>
                </Grid>
              </Grid>
            </motion.section>
        </motion.div>

        <Divider />

        <div className={styles.grid}>
          {projects.map((project) => (
            <motion.button
              key={project.title}
              className={styles.card}
              layoutId={`card-${project.title}`}
              onClick={() => setActive(project)}
              style={{
                cursor: "pointer",
                width: "100%",
                border: `1px solid ${theme.palette.divider}`,
                padding: "1em",
                overflow: "hidden",
                background: alpha(theme.palette.background.paper, theme.palette.mode === 'dark' ? 0.2 : 0.6),
                color: theme.palette.text.primary,
              }}
            >
                <MuiStack direction="column" spacing={{ xs: 1, sm: 2 }} alignItems="flex-start">
                    <Typography component="h3" variant="h6">
                    {project.title}
                    </Typography>
                    <MuiStack 
                        direction="row"
                        columnGap={1}
                        rowGap={1}
                        flexWrap="wrap">
                    {project.tags?.slice(0, 3).map((t) => (
                        <Chip
                          key={t}
                          label={t}
                          size="small"
                          variant="filled"
                          sx={{ bgcolor: 'action.selected', color: 'text.primary' }}
                        />
                    ))}
                    {extractYear(project.title) && (
                        <Chip label={extractYear(project.title)} size="small" color="primary"/>
                    )}
                    </MuiStack>
                </MuiStack>
            </motion.button>
          ))}
        </div>

        <AnimatePresence>
          {active && (
            <ModalCard
              key={active.title}
              project={active}
              onClose={() => setActive(null)}
            />
          )}
        </AnimatePresence>
      </Stack>
  );
}

function ModalCard({ project, onClose }) {
  const [mounted, setMounted] = React.useState(false);
  React.useEffect(() => setMounted(true), []);
  React.useEffect(() => {
    const onKey = (e) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  if (!mounted) return null;

  return createPortal(
    <>
      <motion.div
        className={styles.modalOverlay}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
      />
      <motion.div
        className={styles.modalContainer}
        role="dialog"
        aria-modal="true"
        aria-label={`${project.title} details`}
        layoutId={`card-${project.title}`}
        initial={{ opacity: 0, y: 20, scale: 0.98 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: 10, scale: 0.98 }}
        onClick={(e) => e.stopPropagation()}
      >
        <MuiStack direction="row" justifyContent="space-between" alignItems="start">
          <Typography component="h3" variant="h5" color="text.primary">
            {project.title}
          </Typography>
          <IconButton aria-label="Close" onClick={onClose} size="small">
            <CloseIcon />
          </IconButton>
        </MuiStack>
        <Divider style={{ margin: "12px 0" }} />
        <MuiStack direction="row" spacing={1} flexWrap="wrap" style={{ marginBottom: 8 }}>
          {project.tags?.map((t) => (
            <Chip key={t} label={t} size="small" variant="outlined" />
          ))}
        </MuiStack>
        <Typography component="p" variant="body1" color="text.primary" style={{ opacity: 0.9 }}>
          {project.content}
        </Typography>
        <div style={{ marginTop: 16 }}>
          {project.url === "disabled" ? (
            <Button variant="contained" color="warning" className="m1" endIcon={<SmartphoneIcon />}>
              Unavailable
            </Button>
          ) : (
            <Button variant="contained" className="m1" href={project.url} target="_blank" rel="noreferrer" endIcon={<GitHubIcon />}>
              View
            </Button>
          )}
        </div>
      </motion.div>
    </>,
    document.body
  );
}
